api:
  name: "Traffic Violation"
  service_name: "traffic_violation"
  description: "Mention some high level description about API Functionality"
  version: "0.0.1"
  debug_mode: "True"
  host: 'localhost'
  port: 8002
